name: oft_rl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - farama-notifications=0.0.4=py310h06a4308_0
  - gymnasium=0.28.1=py310h06a4308_1
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jax-jumpy=1.0.0=py310h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libllvm14=14.0.6=hecde1de_4
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - ncurses=6.5=h7934f7d_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2021.8.0=hdb19cb5_0
  - tbb-devel=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.4.0
      - bddl==1.0.1
      - bitsandbytes==0.42.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==2.1.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - easydict==1.9
      - egl-probe==1.0.2
      - einops==0.4.1
      - etils==1.13.0
      - exceptiongroup==1.3.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - flash-attn==2.7.3
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - future==0.18.2
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - grpcio==1.76.0
      - gym==0.25.2
      - gym-notices==0.1.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - hydra-core==1.2.0
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupytext==1.18.1
      - kiwisolver==1.4.9
      - libero==0.1.0
      - llvmlite==0.45.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.5.3
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mujoco==3.3.7
      - nbformat==5.10.4
      - networkx==3.4.2
      - numba==0.62.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.6.0.66
      - packaging==25.0
      - pathtools==0.1.2
      - peft==0.12.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - promise==2.3
      - protobuf==3.20.3
      - psutil==7.1.3
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - robomimic==0.2.0
      - robosuite==1.4.0
      - rpds-py==0.29.0
      - safetensors==0.7.0
      - scipy==1.13.1
      - sentry-sdk==2.46.0
      - setproctitle==1.3.7
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.2.0
      - thop==0.1.1-2209072238
      - timm==0.9.16
      - tokenizers==0.19.1
      - tomli==2.3.0
      - torch==2.2.2
      - torchaudio==2.9.1+cu129
      - torchvision==0.17.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.40.1
      - triton==2.2.0
      - urllib3==2.5.0
      - wandb==0.13.1
      - werkzeug==3.1.3
      - zipp==3.23.0
prefix: /home/abhi/miniconda3/envs/oft_rl
